name: 🐛 Bug report
description: Create a report to help us improve
title: "[BUG] <title>"
labels: ['bug, untriaged']
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Related component
      description: Choose a specific OpenSearch component your bug belongs to.  If you are unsure which to select or if the component is not present, select "Other".
      multiple: false
      options:
        - Other
        - Build
        - Clients
        - Cluster Manager
        - Extensions
        - Indexing:Performance
        - Indexing:Replication
        - Indexing
        - Libraries
        - Plugins
        - Search:Aggregations
        - Search:Performance
        - Search:Query Capabilities
        - Search:Query Insights
        - Search:Relevance
        - Search:Remote Search
        - Search:Resiliency
        - Search:Searchable Snapshots
        - Search
        - Storage:Durability
        - Storage:Performance
        - Storage:Remote
        - Storage:Snapshots
        - Storage
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Details
      description: Add any other context about the problem here.
      value: |
        **Plugins**
        Please list all plugins currently enabled.

        **Screenshots**
        If applicable, add screenshots to help explain your problem.

        **Host/Environment (please complete the following information):**
         - OS: [e.g. iOS]
         - Version [e.g. 22]

        **Additional context**
        Add any other context about the problem here.
    validations:
      required: false
